version: '3.1'
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=timeweb
      - POSTGRES_USER=timeweb
      - POSTGRES_DB=timeweb
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - 5531:5531